// tree_data.svh -- auto-generated by train_tree.cpp
// Flattened decision tree. Root is node 0.
// Semantics: if (feature[feature_index] < threshold) go to left_child; else right_child.
// NOTE: uses logic arrays + initial blocks (not localparam '{...}) for
// compatibility with Icarus Verilog, which does not support array-literal
// initializers on localparam/parameter unpacked arrays.

localparam int NUM_NODES = 5;

logic [7:0] FEATURE_IDX [0:NUM_NODES-1];
logic [7:0] THRESHOLD [0:NUM_NODES-1];
logic [7:0] LEFT_CHILD [0:NUM_NODES-1];
logic [7:0] RIGHT_CHILD [0:NUM_NODES-1];
logic IS_LEAF [0:NUM_NODES-1];
logic [7:0] LEAF_CLASS [0:NUM_NODES-1];

initial begin
    FEATURE_IDX[0] = 2;
    THRESHOLD[0] = 22;
    LEFT_CHILD[0] = 1;
    RIGHT_CHILD[0] = 4;
    IS_LEAF[0] = 1'b0;
    LEAF_CLASS[0] = 0;
    FEATURE_IDX[1] = 1;
    THRESHOLD[1] = 80;
    LEFT_CHILD[1] = 2;
    RIGHT_CHILD[1] = 3;
    IS_LEAF[1] = 1'b0;
    LEAF_CLASS[1] = 0;
    FEATURE_IDX[2] = 0;
    THRESHOLD[2] = 0;
    LEFT_CHILD[2] = 0;
    RIGHT_CHILD[2] = 0;
    IS_LEAF[2] = 1'b1;
    LEAF_CLASS[2] = 1;
    FEATURE_IDX[3] = 0;
    THRESHOLD[3] = 0;
    LEFT_CHILD[3] = 0;
    RIGHT_CHILD[3] = 0;
    IS_LEAF[3] = 1'b1;
    LEAF_CLASS[3] = 0;
    FEATURE_IDX[4] = 0;
    THRESHOLD[4] = 0;
    LEFT_CHILD[4] = 0;
    RIGHT_CHILD[4] = 0;
    IS_LEAF[4] = 1'b1;
    LEAF_CLASS[4] = 0;
end
