// test_vectors.svh -- auto-generated by train_tree.cpp
// Each row: {f0, f1, f2, f3, expected_class}
// NOTE: uses a logic array + initial block (not localparam '{...}) for
// Icarus Verilog compatibility -- see tree_data.svh for details.

localparam int NUM_VECTORS = 14;

logic [7:0] TEST_VECTORS [0:NUM_VECTORS-1][0:4];

initial begin
    TEST_VECTORS[0][0] = 80;
    TEST_VECTORS[0][1] = 60;
    TEST_VECTORS[0][2] = 10;
    TEST_VECTORS[0][3] = 200;
    TEST_VECTORS[0][4] = 1;
    TEST_VECTORS[1][0] = 85;
    TEST_VECTORS[1][1] = 90;
    TEST_VECTORS[1][2] = 5;
    TEST_VECTORS[1][3] = 180;
    TEST_VECTORS[1][4] = 0;
    TEST_VECTORS[2][0] = 70;
    TEST_VECTORS[2][1] = 40;
    TEST_VECTORS[2][2] = 20;
    TEST_VECTORS[2][3] = 150;
    TEST_VECTORS[2][4] = 1;
    TEST_VECTORS[3][0] = 60;
    TEST_VECTORS[3][1] = 30;
    TEST_VECTORS[3][2] = 45;
    TEST_VECTORS[3][3] = 100;
    TEST_VECTORS[3][4] = 0;
    TEST_VECTORS[4][0] = 55;
    TEST_VECTORS[4][1] = 85;
    TEST_VECTORS[4][2] = 25;
    TEST_VECTORS[4][3] = 40;
    TEST_VECTORS[4][4] = 0;
    TEST_VECTORS[5][0] = 90;
    TEST_VECTORS[5][1] = 70;
    TEST_VECTORS[5][2] = 15;
    TEST_VECTORS[5][3] = 220;
    TEST_VECTORS[5][4] = 1;
    TEST_VECTORS[6][0] = 75;
    TEST_VECTORS[6][1] = 95;
    TEST_VECTORS[6][2] = 30;
    TEST_VECTORS[6][3] = 60;
    TEST_VECTORS[6][4] = 0;
    TEST_VECTORS[7][0] = 65;
    TEST_VECTORS[7][1] = 50;
    TEST_VECTORS[7][2] = 8;
    TEST_VECTORS[7][3] = 120;
    TEST_VECTORS[7][4] = 1;
    TEST_VECTORS[8][0] = 50;
    TEST_VECTORS[8][1] = 88;
    TEST_VECTORS[8][2] = 35;
    TEST_VECTORS[8][3] = 30;
    TEST_VECTORS[8][4] = 0;
    TEST_VECTORS[9][0] = 95;
    TEST_VECTORS[9][1] = 45;
    TEST_VECTORS[9][2] = 50;
    TEST_VECTORS[9][3] = 240;
    TEST_VECTORS[9][4] = 0;
    TEST_VECTORS[10][0] = 45;
    TEST_VECTORS[10][1] = 92;
    TEST_VECTORS[10][2] = 40;
    TEST_VECTORS[10][3] = 20;
    TEST_VECTORS[10][4] = 0;
    TEST_VECTORS[11][0] = 88;
    TEST_VECTORS[11][1] = 55;
    TEST_VECTORS[11][2] = 18;
    TEST_VECTORS[11][3] = 210;
    TEST_VECTORS[11][4] = 1;
    TEST_VECTORS[12][0] = 72;
    TEST_VECTORS[12][1] = 35;
    TEST_VECTORS[12][2] = 55;
    TEST_VECTORS[12][3] = 160;
    TEST_VECTORS[12][4] = 0;
    TEST_VECTORS[13][0] = 68;
    TEST_VECTORS[13][1] = 42;
    TEST_VECTORS[13][2] = 12;
    TEST_VECTORS[13][3] = 130;
    TEST_VECTORS[13][4] = 1;
end
